#!/bin/bash

set -e
set -u
#set -o pipefail

#echo "" >.env

AIRFLOW_SERVICES='airflow_airflow'

while getopts 'f:' opt; do
  case "$opt" in
    f)
     #flush logs
    AIRFLOW_SERVICES='airflow_'
    echo $OPTARG
    ;;
    ?)
      _usage
      ;;
  esac
done

echo "aaargs $#"
echo "optin $OPTIND"

shift "$(($OPTIND -1))"

echo "optin $OPTIND"
echo "args $#"
Command=""
if [[ $# -gt 0 ]]; then
  Command=$1

fi

echo "Command : $Command"
echo "Airflow services : $AIRFLOW_SERVICES"


case "$Command" in

  start)
    echo "Starting Airflow Service"
    docker-compose up -d
  ;;

  stop)
    echo "Stoping Airflow Basic services"
    docker stop $(docker ps | grep $AIRFLOW_SERVICES  |  awk {'print $1'})    
  ;;

  build)
    echo "building airflow"
    docker-compose -f docker-prod.yml build airflow-webserver
    docker push linkaform/airflow:latest
  ;;

esac
